conn = new Mongo(); 
db = conn.getDB('media'); 
db.pics.insert({"file_name":"Darwin and Joi.mp4","path":"/seagate/videos/02052013/"});
db.pics.insert({"file_name":"GEDC2698.MOV","path":"/seagate/videos/02122012/"});
db.pics.insert({"file_name":"GEDC2699.MOV","path":"/seagate/videos/02122012/"});
db.pics.insert({"file_name":"GEDC2757.MOV","path":"/seagate/videos/02122012/"});
db.pics.insert({"file_name":"GEDC2758.MOV","path":"/seagate/videos/02122012/"});
db.pics.insert({"file_name":"GEDC2807.MOV","path":"/seagate/videos/02122012/"});
db.pics.insert({"file_name":"GEDC2818.MOV","path":"/seagate/videos/02122012/"});
db.pics.insert({"file_name":"IMG_0162.MOV","path":"/seagate/videos/02122012/"});
db.pics.insert({"file_name":"IMG_0200.MOV","path":"/seagate/videos/02122012/"});
db.pics.insert({"file_name":"IMG_0201.MOV","path":"/seagate/videos/02122012/"});
db.pics.insert({"file_name":"IMG_0203.MOV","path":"/seagate/videos/02122012/"});
db.pics.insert({"file_name":"IMG_0205.MOV","path":"/seagate/videos/02122012/"});
db.pics.insert({"file_name":"GEDC2699.MOV","path":"/seagate/videos/03052012/"});
db.pics.insert({"file_name":"GEDC2757.MOV","path":"/seagate/videos/03052012/"});
db.pics.insert({"file_name":"GEDC2758.MOV","path":"/seagate/videos/03052012/"});
db.pics.insert({"file_name":"GEDC2807.MOV","path":"/seagate/videos/03052012/"});
db.pics.insert({"file_name":"GEDC2818.MOV","path":"/seagate/videos/03052012/"});
db.pics.insert({"file_name":"GEDC2819.MOV","path":"/seagate/videos/03052012/"});
db.pics.insert({"file_name":"GEDC2835.MOV","path":"/seagate/videos/03052012/"});
db.pics.insert({"file_name":"GEDC2840.MOV","path":"/seagate/videos/03052012/"});
db.pics.insert({"file_name":"GEDC2841.MOV","path":"/seagate/videos/03052012/"});
db.pics.insert({"file_name":"GEDC2842.MOV","path":"/seagate/videos/03052012/"});
db.pics.insert({"file_name":"GEDC2843.MOV","path":"/seagate/videos/03052012/"});
db.pics.insert({"file_name":"IMG_0218.mov","path":"/seagate/videos/06162012/"});
db.pics.insert({"file_name":"IMG_0167.mov","path":"/seagate/videos/06262012/"});
db.pics.insert({"file_name":"IMG_0169.mov","path":"/seagate/videos/06262012/"});
db.pics.insert({"file_name":"IMG_0171.mov","path":"/seagate/videos/06262012/"});
db.pics.insert({"file_name":"IMG_0187.mov","path":"/seagate/videos/06262012/"});
db.pics.insert({"file_name":"IMG_0218.mov","path":"/seagate/videos/06262012/"});
db.pics.insert({"file_name":"IMG_0230.mp4","path":"/seagate/videos/06262012/"});
db.pics.insert({"file_name":"IMG_0396.mov","path":"/seagate/videos/08142012/"});
db.pics.insert({"file_name":"IMG_0398.mov","path":"/seagate/videos/08142012/"});
db.pics.insert({"file_name":"IMG_0422.mov","path":"/seagate/videos/08222012/"});
db.pics.insert({"file_name":"IMG_0423.mov","path":"/seagate/videos/08232012/"});
db.pics.insert({"file_name":"IMG_0457.mov","path":"/seagate/videos/09022012/"});
db.pics.insert({"file_name":"IMG_0500.mov","path":"/seagate/videos/09192012/"});
db.pics.insert({"file_name":"IMG_0697.mov","path":"/seagate/videos/11022012/"});
db.pics.insert({"file_name":"GEDC1571.MOV","path":"/seagate/videos/12-18-2011/"});
db.pics.insert({"file_name":"GEDC1668.MOV","path":"/seagate/videos/12-18-2011/"});
db.pics.insert({"file_name":"GEDC1669.MOV","path":"/seagate/videos/12-18-2011/"});
db.pics.insert({"file_name":"GEDC1746.MOV","path":"/seagate/videos/12-18-2011/"});
db.pics.insert({"file_name":"GEDC1747.MOV","path":"/seagate/videos/12-18-2011/"});
db.pics.insert({"file_name":"GEDC1748.MOV","path":"/seagate/videos/12-18-2011/"});
db.pics.insert({"file_name":"GEDC1749.MOV","path":"/seagate/videos/12-18-2011/"});
db.pics.insert({"file_name":"GEDC1876.MOV","path":"/seagate/videos/12-18-2011/"});
db.pics.insert({"file_name":"GEDC1877.MOV","path":"/seagate/videos/12-18-2011/"});
db.pics.insert({"file_name":"GEDC1878.MOV","path":"/seagate/videos/12-18-2011/"});
db.pics.insert({"file_name":"GEDC1907.MOV","path":"/seagate/videos/12-18-2011/"});
db.pics.insert({"file_name":"GEDC1926.MOV","path":"/seagate/videos/12-18-2011/"});
db.pics.insert({"file_name":"Mini Pop_Like I Do.mp4","path":"/seagate/videos/2008-09/"});
db.pics.insert({"file_name":"Travel.mp4","path":"/seagate/videos/2008-09/"});
db.pics.insert({"file_name":"Hints and Tips 1 - Music Download.mp4","path":"/seagate/videos/2008-10/"});
db.pics.insert({"file_name":"Hints and Tips 2 -Contacts Bar.mp4","path":"/seagate/videos/2008-10/"});
db.pics.insert({"file_name":"Hints and Tips 3 - Key Tips and Shortcuts.mp4","path":"/seagate/videos/2008-10/"});
db.pics.insert({"file_name":"Hints and Tips 4 - Input Methods.mp4","path":"/seagate/videos/2008-10/"});
db.pics.insert({"file_name":"Hints and Tips 6 - OVI on 5800 XpressMusic.mp4","path":"/seagate/videos/2008-10/"});
db.pics.insert({"file_name":"Hints and Tips and 5 - Music Transfer.mp4","path":"/seagate/videos/2008-10/"});
db.pics.insert({"file_name":"Nokia 5800 XpressMusic.mp4","path":"/seagate/videos/2008-10/"});
db.pics.insert({"file_name":"PrisM-ToyStoryCAM.avi","path":"/seagate/videos/2010-06/"});
db.pics.insert({"file_name":"Thumbs.db","path":"/seagate/videos/2010-06/"});
db.pics.insert({"file_name":"08152010002.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08152010003.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08152010004.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08152010005.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08152010006.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08152010007.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08152010008.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08152010009.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08222010011.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08222010012.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08222010013.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08272010015.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08302010016.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08302010017.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"08302010018.mp4","path":"/seagate/videos/2010-08/"});
db.pics.insert({"file_name":"09122010019.mp4","path":"/seagate/videos/2010-09/"});
db.pics.insert({"file_name":"47104 (1).mp4","path":"/seagate/videos/2010-09/"});
db.pics.insert({"file_name":"Jolo thé javawalkies023.mp4","path":"/seagate/videos/2010-10/"});
db.pics.insert({"file_name":"Jolo thé javawalkies024.mp4","path":"/seagate/videos/2010-10/"});
db.pics.insert({"file_name":"Jolo thé javawalkies025.mp4","path":"/seagate/videos/2010-10/"});
db.pics.insert({"file_name":"Tino Ang Dapat Titihin.3gp","path":"/seagate/videos/2010-10/"});
db.pics.insert({"file_name":"Jolo thé javawalkies027.mp4","path":"/seagate/videos/2010-11/"});
db.pics.insert({"file_name":"Jolo thé javawalkies032.mp4","path":"/seagate/videos/2010-11/"});
db.pics.insert({"file_name":"Jolo thé javawalkies033.mp4","path":"/seagate/videos/2010-11/"});
db.pics.insert({"file_name":"Jolo thé javawalkies034.mp4","path":"/seagate/videos/2010-11/"});
db.pics.insert({"file_name":"Jolo thé javawalkies035.mp4","path":"/seagate/videos/2010-11/"});
db.pics.insert({"file_name":"Jolo thé javawalkies036.mp4","path":"/seagate/videos/2010-11/"});
db.pics.insert({"file_name":"Jolo thé javawalkies038.mp4","path":"/seagate/videos/2010-12/"});
db.pics.insert({"file_name":"Jolo thé javawalkies039.mp4","path":"/seagate/videos/2010-12/"});
db.pics.insert({"file_name":"Jolo thé javawalkies040.mp4","path":"/seagate/videos/2010-12/"});
db.pics.insert({"file_name":"Jolo thé javawalkies041.mp4","path":"/seagate/videos/2010-12/"});
db.pics.insert({"file_name":"Jolo thé javawalkies042.mp4","path":"/seagate/videos/2011-01/"});
db.pics.insert({"file_name":"Jolo thé javawalkies043.mp4","path":"/seagate/videos/2011-01/"});
db.pics.insert({"file_name":"Jolo thé javawalkies049.mp4","path":"/seagate/videos/2011-02/"});
db.pics.insert({"file_name":"Jolo thé javawalkies050.mp4","path":"/seagate/videos/2011-02/"});
db.pics.insert({"file_name":"Jolo thé javawalkies051.mp4","path":"/seagate/videos/2011-02/"});
db.pics.insert({"file_name":"Jolo thé javawalkies052.mp4","path":"/seagate/videos/2011-02/"});
db.pics.insert({"file_name":"Jolo thé javawalkies053.mp4","path":"/seagate/videos/2011-02/"});
db.pics.insert({"file_name":"Jolo thé javawalkies054.mp4","path":"/seagate/videos/2011-02/"});
db.pics.insert({"file_name":"Jolo thé javawalkies055.mp4","path":"/seagate/videos/2011-02/"});
db.pics.insert({"file_name":"Jolo thé javawalkies056.mp4","path":"/seagate/videos/2011-02/"});
db.pics.insert({"file_name":"Jolo thé javawalkies057.mp4","path":"/seagate/videos/2011-02/"});
db.pics.insert({"file_name":"Jolo thé javawalkies058.mp4","path":"/seagate/videos/2011-02/"});
db.pics.insert({"file_name":"Jolo thé javawalkies059.mp4","path":"/seagate/videos/2011-02/"});
db.pics.insert({"file_name":"Jolo thé javawalkies061.mp4","path":"/seagate/videos/2011-02/"});
db.pics.insert({"file_name":"Jolo thé javawalkies062.mp4","path":"/seagate/videos/2011-02/"});
db.pics.insert({"file_name":"Jolo thé javawalkies063.mp4","path":"/seagate/videos/2011-03/"});
db.pics.insert({"file_name":"Jolo thé javawalkies064.mp4","path":"/seagate/videos/2011-03/"});
db.pics.insert({"file_name":"Video0000.3gp","path":"/seagate/videos/2011-03/"});
db.pics.insert({"file_name":"Video0001.3gp","path":"/seagate/videos/2011-03/"});
db.pics.insert({"file_name":"Video0002.3gp","path":"/seagate/videos/2011-03/"});
db.pics.insert({"file_name":"Video0003.3gp","path":"/seagate/videos/2011-03/"});
db.pics.insert({"file_name":"GEDC1934 (2).MOV","path":"/seagate/videos/"});
db.pics.insert({"file_name":"GEDC1934.MOV","path":"/seagate/videos/"});
db.pics.insert({"file_name":"GEDC1940.MOV","path":"/seagate/videos/"});
db.pics.insert({"file_name":"GEDC1941.MOV","path":"/seagate/videos/"});
db.pics.insert({"file_name":"GEDC1942.MOV","path":"/seagate/videos/"});
db.pics.insert({"file_name":"Jolo thé javawalkies059.mp4","path":"/seagate/videos/Nokia Video Manager/"});
db.pics.insert({"file_name":"Jolo thé javawalkies064.mp4","path":"/seagate/videos/Nokia Video Manager/"});
db.pics.insert({"file_name":"3 idiots.mov","path":"/seagate/videos/for ipod/"});
db.pics.insert({"file_name":"47510.mov","path":"/seagate/videos/for ipod/"});
db.pics.insert({"file_name":"from this moment.mov","path":"/seagate/videos/for ipod/"});
db.pics.insert({"file_name":"fvid.mp4","path":"/seagate/videos/for ipod/"});
db.pics.insert({"file_name":"man vs wild 1.mp4","path":"/seagate/videos/for ipod/"});
db.pics.insert({"file_name":"man vs wild 2.mp4","path":"/seagate/videos/for ipod/"});
db.pics.insert({"file_name":"man vs wild 3 .mp4","path":"/seagate/videos/for ipod/"});
db.pics.insert({"file_name":"sherlockholmes.mov","path":"/seagate/videos/for ipod/"});
db.pics.insert({"file_name":"man vs wild-10.mp4","path":"/seagate/videos/for ipod/tmp/"});
db.pics.insert({"file_name":"man vs wild-11.mp4","path":"/seagate/videos/for ipod/tmp/"});
db.pics.insert({"file_name":"man vs wild-12.mp4","path":"/seagate/videos/for ipod/tmp/"});
db.pics.insert({"file_name":"man vs wild-13.mp4","path":"/seagate/videos/for ipod/tmp/"});
db.pics.insert({"file_name":"man vs wild-4.mp4","path":"/seagate/videos/for ipod/tmp/"});
db.pics.insert({"file_name":"man vs wild-5.mp4","path":"/seagate/videos/for ipod/tmp/"});
db.pics.insert({"file_name":"man vs wild-6.mp4","path":"/seagate/videos/for ipod/tmp/"});
db.pics.insert({"file_name":"man vs wild-7.mp4","path":"/seagate/videos/for ipod/tmp/"});
db.pics.insert({"file_name":"man vs wild-8.mp4","path":"/seagate/videos/for ipod/tmp/"});
db.pics.insert({"file_name":"man vs wild-9.mp4","path":"/seagate/videos/for ipod/tmp/"});
db.pics.insert({"file_name":"unknown_universe.mp4","path":"/seagate/videos/for ipod/"});
db.pics.insert({"file_name":"worm hole.mp4","path":"/seagate/videos/for ipod/"});
db.pics.insert({"file_name":"joi bday 2014.mp4","path":"/seagate/videos/"});
db.pics.insert({"file_name":"jolo.wlmp","path":"/seagate/videos/"});
db.pics.insert({"file_name":"dependency-inversion.mp4","path":"/seagate/videos/laravel/april 22/"});
db.pics.insert({"file_name":"interface-segregation.mp4","path":"/seagate/videos/laravel/april 22/"});
db.pics.insert({"file_name":"ioc.mp4","path":"/seagate/videos/laravel/april 22/"});
db.pics.insert({"file_name":"liskov.mp4","path":"/seagate/videos/laravel/april 22/"});
db.pics.insert({"file_name":"open-closed.mp4","path":"/seagate/videos/laravel/april 22/"});
db.pics.insert({"file_name":"repositories.mp4","path":"/seagate/videos/laravel/april 22/"});
db.pics.insert({"file_name":"single-reponsibility.mp4","path":"/seagate/videos/laravel/april 22/"});
db.pics.insert({"file_name":"extract packages.mp4","path":"/seagate/videos/laravel/"});
db.pics.insert({"file_name":"failed job.mp4","path":"/seagate/videos/laravel/"});
db.pics.insert({"file_name":"phpspecs.mp4","path":"/seagate/videos/laravel/"});
db.pics.insert({"file_name":"beanstlalkd.mp4","path":"/seagate/videos/laravel/queue/"});
db.pics.insert({"file_name":"failed-jobs-interrogation.mp4","path":"/seagate/videos/laravel/queue/"});
db.pics.insert({"file_name":"queue.mp4","path":"/seagate/videos/laravel/queue/"});
db.pics.insert({"file_name":"supervisord.mp4","path":"/seagate/videos/laravel/queue/"});
db.pics.insert({"file_name":"supervise this.mp4","path":"/seagate/videos/laravel/"});
db.pics.insert({"file_name":"travis.mp4","path":"/seagate/videos/laravel/"});
db.pics.insert({"file_name":"view presenters.mp4","path":"/seagate/videos/laravel/"});
db.pics.insert({"file_name":"01 - Joi Biography.mov","path":"/seagate/videos/wedding avp/"});
db.pics.insert({"file_name":"02 - Darwin Biography.mov","path":"/seagate/videos/wedding avp/"});
db.pics.insert({"file_name":"04 - Love Story.mov","path":"/seagate/videos/wedding avp/"});
db.pics.insert({"file_name":"05- Wedding Preparation.mov","path":"/seagate/videos/wedding avp/"});
db.pics.insert({"file_name":"06 - Wedding Trailer.mov","path":"/seagate/videos/wedding avp/"});
db.pics.insert({"file_name":"07 - wedding day.mp4","path":"/seagate/videos/wedding avp/"});
